### ISSUE TITLE
Does not build with GHC-9.0 due to TH failure

### ISSUE THREAD

**Issue by noinia** [chessai/vector-circular#10]
This package currently does not build with ghc 9.0 yet due to an upperbound on template-haskell. When I bumped the bound on template-haskell to 0.18 compilation fails with: 

```
src/Data/Vector/Circular.hs:330:15: error:
    • Couldn't match type: TExp a0
                     with: CircularVector a
      Expected: CircularVector a -> Code m (CircularVector a)
        Actual: CircularVector a -> Code m (TExp a0)
    • In the expression: unsafeTExpCoerce . lift
      In an equation for ‘liftTyped’: liftTyped = unsafeTExpCoerce . lift
      In the instance declaration for ‘Lift (CircularVector a)’
    • Relevant bindings include
        liftTyped :: CircularVector a -> Code m (CircularVector a)
          (bound at src/Data/Vector/Circular.hs:330:3)
    |
330 |   liftTyped = unsafeTExpCoerce . lift
    |               ^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Vector/Circular.hs:560:3: error:
    • Couldn't match expected type: Q (TExp (CircularVector a))
                  with actual type: Code m0 (CircularVector a)
    • In the expression: liftTyped (unsafeFromList xs)
      In an equation for ‘vec’: vec xs = liftTyped (unsafeFromList xs)
    • Relevant bindings include
        xs :: [a] (bound at src/Data/Vector/Circular.hs:558:5)
        vec :: [a] -> Q (TExp (CircularVector a))
          (bound at src/Data/Vector/Circular.hs:557:1)
    |
560 |   liftTyped (unsafeFromList xs)
```
I might have a more detailed look on how to fix it later.

**Comment by chessai** [comment]
Thanks for reporting. Indeed TH has changed a lot in the most recent major version bump. The fix should be simple, I just haven't put one together yet. If you have time to fix that would be great.
